#
# Copyright (c) 2026. Bernard Bou <1313ou@gmail.com>
#
as_words=w
# column artifacts
groupings=groupings
nullsynset=nullsynset
# group_concats
classes=classes
frames=frames
examples=examples
sampleset=sampleset
definitions=definitions